### ISSUE TITLE
Regarding octernship task

### ISSUE THREAD

**Issue by Ghost1129** [SecureStackCo/SecureStack-Octernship#4]
Hi Need some help regarding the bug finding task is there discussion forum or discord server where i can get help

The source code which is provided has no src file as such I have made account in securestack and added the url it provided various issues and vulnerabilities further need help

**Comment by 6mile** [comment]
I've updated the source code link:  https://github.com/SecureStackCo/app.cheapcryptobank.com

**Comment by Ghost1129** [comment]
hi still there are no project file are we are supposed to just find vurnabilities using tool only

**Comment by 6mile** [comment]
I just pushed the /src folder to the repo

**Comment by Ghost1129** [comment]
thanks
