### ISSUE TITLE
Related Task Submisson 

### ISSUE THREAD

**Issue by 11WALTER11** [SecureStackCo/SecureStack-Octernship#6]
Hello, @ashwinexe @6mile @paulmccarty 

I am unable to apply for this project at this time as all slots are currently filled. However, I am still highly interested in this project. Would it be possible for me to fork this repository and create a pull request once the task is completed?

**Comment by 6mile** [comment]
Yes, of course, please do!  In the meantime, I will research the number of slots and see if I can increase it.

**Comment by 11WALTER11** [comment]
Thanks for the reply, @6mile . 
I will raise a PR here once I'm done with the task
