### ISSUE TITLE
Few Questions Related to Octernship Task

### ISSUE THREAD

**Issue by JRS296** [SecureStackCo/SecureStack-Octernship#7]
Hello @6mile @ashwinexe @paulmccarty ! Hope you all are well.

I have applied for the SecureStack Octernship, and am eager to start work on the task at hand. I would like to ask few questions pertaining to the given  task before I get started:

1. Are we to include multiple branches for different vulnerabilities that we encounter, or are we to specify all of our findings within a single branch?
2. May I know the general criteria for judging the completed task? And are we to add any further credentials like Resumes and a brief introduction to better supplement our applications?

Also, kindly enable GitHub Discussions to help further facilitate discussion pertaining to the task in the GitHub Classroom repositories.
Thank you once again for your time, looking forward to working with the SecureStack team!

**Comment by 6mile** [comment]
Answers to your questions:
1. No, please put all findings in one branch if possible.
2. We will ask for follow up documents based on performance in this initial task.  
3. I have enabled Discussions for the repository.  Thanks for pointing this out.

**Comment by Exoutia** [comment]
> Answers to your questions:
> 
>     1. No, please put all findings in one branch if possible.
> 
>     2. We will ask for follow up documents based on performance in this initial task.
> 
>     3. I have enabled Discussions for the repository.  Thanks for pointing this out.

@6mile  I also wanted to ask about the github discussion is it the discussion in this repo or the repo that is created by classroom as mine repo doesnot have discussion option enabled

**Comment by ashwinexe** [comment]
> > Answers to your questions:
> > ```
> > 1. No, please put all findings in one branch if possible.
> > 
> > 2. We will ask for follow up documents based on performance in this initial task.
> > 
> > 3. I have enabled Discussions for the repository.  Thanks for pointing this out.
> > ```
> 
> @6mile I also wanted to ask about the github discussion is it the discussion in this repo or the repo that is created by classroom as mine repo doesnot have discussion option enabled

This repository. `private` repositories are not accessible by everyone and hence discussions are not enabled on them.

**Comment by JRS296** [comment]
Thank you @6mile and @ashwinexe for clearing the same 👍
